# Generated by Django 5.2.10 on 2026-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.JSONField()),
                ('action', models.JSONField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('device_metric_id', models.BigIntegerField(db_index=True)),
            ],
            options={
                'db_table': 'rules',
                'indexes': [
                    models.Index(fields=['device_metric_id'], name='idx_rules_device_metric_id'),
                    models.Index(fields=['is_active'], name='idx_rules_is_active'),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('device_metric_id', 'name'),
                        name='unique_rule_name_per_device_metric_id',
                    )
                ],
            },
        ),
    ]
