name: ${COMPOSE_PROJECT_NAME:-rule-engine-service}

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    restart: always
    ports:
      - "5433:8080"
    environment:
      SWAGGER_JSON: /docs/api.yaml
    volumes:
      - ../docs:/docs
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - rule-engine-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend

  redis:
    image: redis:7.0-alpine3.19
    command: redis-server --appendonly yes
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  rule-engine:
    container_name: rule-engine
    build:
      context: ..
      dockerfile: docker/django/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy  
    restart: unless-stopped
    networks:
      - backend

volumes:
  rule-engine-db-data:
  redis_data:

networks:
  backend:
    driver: bridge  